# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_clientes_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='detalles',
        ),
    ]
